### ISSUE TITLE
Print Command

### ISSUE THREAD

**Issue by bangyen** [4D4850/processor.txt#6]
When using the `-a` option, is the newline after each character intentional?

**Comment by 4D4850** [comment]
No. However, I don't know how to fix it, though I'll look into it.

**Comment by bangyen** [comment]
How about when the `-a` option is *not* used?

**Comment by 4D4850** [comment]
That wasn't initially intended for without -a, but it's appreciated since it makes the numbers understandable.

**Comment by 4D4850** [comment]
Fixed the issue.
