### ISSUE TITLE
Loop Commands

### ISSUE THREAD

**Issue by bangyen** [4D4850/processor.txt#7]
Do you still need help with implementing the loop commands described on the [wiki](https://esolangs.org/wiki/Processor.txt), or are they being removed from the language?

**Comment by 4D4850** [comment]
Loop commands are functional now. The fix was to use a while loop rather than a for loop.

**Comment by 4D4850** [comment]
Issue closed as fixed

**Comment by bangyen** [comment]
Where are the loop commands in the interpreter?

**Comment by 4D4850** [comment]
Whoops. At some point I accidentally removed them. I'll add them back in.
